name: Django Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    env:
      GAR_LOCATION: us-central1 
      GKE_CLUSTER: cluster-1    
      GKE_ZONE: us-central1-c   
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Read Config.JSON file
      id: read_config
      run: |
        sudo apt-get install -y jq
        config=$(cat config.json | jq -r '. | to_entries | map("\(.key)=\(.value)") | .[]')
        echo "$config" >> $GITHUB_ENV
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: e00049-project-workspace

    - name: Configure Docker for GAR
      run: gcloud auth configure-docker

    - name: Docker Build and Push
      if: env.Docker_Build_Push == 'yes'
      run: |
        docker rmi us-central1-docker.pkg.dev/e00049-project-workspace/django/django:latest || true
        docker build -t us-central1-docker.pkg.dev/e00049-project-workspace/django/django:latest -f Dockerfile.django .
        docker tag us-central1-docker.pkg.dev/e00049-project-workspace/django/django:latest us-central1-docker.pkg.dev/e00049-project-workspace/django/django:${{ github.run_number }}
        docker push us-central1-docker.pkg.dev/e00049-project-workspace/django/django:${{ github.run_number }}
        docker rmi us-central1-docker.pkg.dev/e00049-project-workspace/django/django:${{ github.run_number }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    - name: Fresh Deployment Kubernetes Django
      if: env.Fresh_Deploy_Django == 'yes'
      run: |
        sed -i s/latest/${{ github.run_number }}/g deployments/backend/backend-04-django-deployment.yaml
        kubectl apply -f deployments/namespace/01-backend-ns.yml
        kubectl apply -f deployments/backend/

    - name: Update Deployment Kubernetes Django
      if: env.Update_Deploy_Django == 'yes'
      run: kubectl -n dev set image deployment/django-deployment django=us-central1-docker.pkg.dev/e00049-project-workspace/django/django:${{ github.run_number }}
