name: Django Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    steps:
    - name: Checkout
      uses: actions/checkout@v4  
      with:
        ref: dev            

    - name: Read Config.JSON file
      id: read_config
      run: |
        pwd; ls -ll 
        
