name: Django Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout SCM for Django
      uses: actions/checkout@2
      with:
        ref: dev

    - name: Read Config.JSON file
      id: read_config
      run: |
        pwd; ls -ll 
        
