name: Django Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Read Config.JSON file
      id: read_config
      run: |
        sudo apt-get install -y jq
        pwd; ls -ll
        config=$(cat config.json | jq -r '. | to_entries | map("\(.key)=\(.value)") | .[]')
        echo "$config"
        echo "$config" >> $GITHUB_ENV
