name: Django Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    env:
      GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
      GAR_LOCATION: us-central1 
      GKE_CLUSTER: cluster-1    
      GKE_ZONE: us-central1-c   
  

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Read Config.JSON file
      id: read_config
      run: |
        sudo apt-get install -y jq
        config=$(cat config.json | jq -r '. | to_entries | map("\(.key)=\(.value)") | .[]')
        echo "$config" >> $GITHUB_ENV
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        project_id: e00049-project-workspace

    - name: Authenticate Kubernetes Cluster
      run: |
      gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project e00049-project-workspace
      if [ -f ~/.kube/config ]; then
       cat ~/.kube/config
      fi 
