name: Django Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    env:
      # GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
      GAR_LOCATION: us-central1 
      GKE_CLUSTER: cluster-1    
      GKE_ZONE: us-central1-c   
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Read Config.JSON file
      id: read_config
      run: |
        sudo apt-get install -y jq
        config=$(cat config.json | jq -r '. | to_entries | map("\(.key)=\(.value)") | .[]')
        echo "$config" >> $GITHUB_ENV
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: e00049-project-workspace

    # gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project e00049-project-workspace
    - name: Authenticate Kubernetes Cluster
      run: |
        gcloud artifacts repositories list --location=us-central1

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project e00049-project-workspace
    - name: Authenticate Kubernetes Cluster
      run: |
        if [ -f ~/.kube/config ]; then
          cat ~/.kube/config
        fi
